komorasoft/blueprints/users/models.py
from flask_login import UserMixin
from komorasoft.app import db
from sqlalchemy import UniqueConstraint


class User(db.Model, UserMixin):
    __tablename__ = 'uporabniki'

    uid = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    password = db.Column(db.String, nullable=False)
    role = db.Column(db.String, nullable=False)
    description = db.Column(db.String)

    __table_args__ = (
        UniqueConstraint('username', name='uq_username'),
    )

    def __repr__(self):
        return f"Uporabnik:    {self.username},        vloga:    {self.role}"
    
    def get_id(self):
        return self.uid

komorasoft/blueprints/users/routes.py
from flask import request, render_template, redirect, url_for, Blueprint
from komorasoft.blueprints.users.models import User

from flask_login import login_user, logout_user, current_user, login_required

users = Blueprint('users', __name__, template_folder='templates')


def register_user_routes(app, db, bcrypt):
    @users.route('/')
    def index():
        users = User.query.all()
        if current_user.is_authenticated:
            return render_template('users/index.html', users=users, current_user=current_user)
        else:
            return render_template('users/index.html', users=users, current_user=None)


    @users.route('/signup', methods=['GET', 'POST'])
    def signup():
        if request.method == 'GET':
            return render_template('users/signup.html')
        elif request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            role = request.form.get('role')
            desc = request.form.get('description')
            desc = desc if desc != '' else None # if defined, add description

            # Check if user already exists
            existing_users = User.query.all()
            existing_usernames = [user.username for user in existing_users]

            if username not in existing_usernames:
                hashed_password = bcrypt.generate_password_hash(password) # store only hash of the passwd into the database

                user = User(username=username, password=hashed_password, role=role, description=desc) # add new user

                db.session.add(user)
                db.session.commit()
                return redirect(url_for('users.index'))
            else:
                return render_template('users/user_exists.html')


    @users.route('/login', methods=['GET', 'POST'])
    def login():
        if request.method == 'GET':
            return render_template('users/login.html')
        elif request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            next = request.form.get('next') # which page did the user login from

            user = User.query.filter(User.username == username).first()

            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(next)
            else:
                return 'Neuspešen vpis'
            
    @users.route('/delete', methods=['GET', 'POST'])
    @login_required
    def delete():
        if request.method == 'GET':
            users = User.query.all()
            return render_template('users/delete.html', users=users)
        elif request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')

            user = User.query.filter(User.username == username).first()

            if bcrypt.check_password_hash(user.password, password) and current_user.role == "Administrator":
                db.session.delete(user)
                db.session.commit()
                return redirect(url_for('users.index'))
            else:
                return render_template('users/not_authorized.html')

    @users.route('/logout', methods=['GET','POST'])
    def logout():
        if request.method == 'POST':
            next = request.form.get('next')
            logout_user()
            return redirect(next)
        else:
            return redirect(next)
    

komorasoft/blueprints/users/templates/users/delete.html
{% extends "base.html" %}
{% block title %}Odstrani uporabnika{% endblock %}

{% block content %}
<h1>Odstrani uporabnika</h1>
    <ul>
        {% for user in users %}
            <li>{{user}}</li>
        {% endfor %}
    </ul>
<form class="was-validated" data-bs-theme="dark" action="{{url_for('users.delete')}}" method="POST">
    <input type="text" name="username" placeholder="Ime" required="required"><br>
    <input type="password" name="password" id="geslo" required="required"><br>
    <input type="submit" value="Izbriši uporabniški račun.">
</form>
{% endblock %}

komorasoft/blueprints/users/templates/users/index.html
{% extends "base.html" %}
{% block title %}Uporabniki{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
        <h1>Pozdravljeni, {{current_user.username}}</h1>
        <ul>
            {% for user in users %}
                <li>{{user}}</li>
            {% endfor %}
        </ul>
        <br>
        <a href="{{url_for('users.login')}}">Vpis</a><br>
        <a href="{{url_for('users.signup')}}">Dodaj uporabnika</a><br>
        <a href="{{url_for('users.delete')}}">Izbriši uporabnika</a><br>
        <a href="{{url_for('users.logout')}}">Izpis</a><br>
    {% else %}
        <div class="card bg-dark mx-auto p-2" style="width: 18rem;">
            <center><h3>Nisi pooblaščen!</h3></center>
            <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="red"  class="bi bi-ban mx-auto p-2" viewBox="0 0 16 16">
                <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
            </svg>
            <div class="card-body">
            <h5 class="card-title">Žal nimaš dovoljenj!</h5>
            <p class="card-text">Tega dejanja ne moreš izvesti, saj nimaš ustreznih pravic. Za več info kontaktiraj administratorja.</p>
            <a href="{{url_for('core.index')}}" class="btn btn-primary">Nazaj</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

komorasoft/blueprints/users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Vpis{% endblock %}

{% block content %}
<h1>Pozdravljeni v KomoraSOFT programu.</h1>
<h2>Vpiši se v račun.</h2><br>
<div class="container-lg">
    <form class="was-validated" data-bs-theme="dark" action="{{url_for('users.login')}}" method="POST">
        <input type="hidden" name="next" value="{{url_for('core.index')}}">
        <input type="text" name="username" placeholder="Ime" required="required"><br>
        <input type="password" name="password" placeholder="Geslo" id="geslo" required="required">
        <input type="submit" value="Vpis">
    </form><br>
</div>
{% endblock %}

komorasoft/blueprints/users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Prijava{% endblock %}

{% block content %}
<h1>Pozdravljeni v KomoraSOFT programu.</h1>
<h2>Ustvarjanje novega uporabnika</h2>
<form class="was-validated" data-bs-theme="dark" action="{{url_for('users.signup')}}" method="POST">
    <input type="text" name="username" placeholder="Ime" required="required"><br>
    <input type="password" name="password" id="geslo" value="Geslo" required="required"><br>
    <input type="text" name="description" placeholder="Opis"><br>
    <input type="radio" name="role" id="uporabnik", value="Uporabnik">
    <label for="uporabnik">Uporabnik</label><br>
    <input type="radio" name="role" id="admin", value="Administrator">
    <label for="admin">Administrator</label><br>
    <input type="submit" value="Prijava">
</form>
{% endblock %}

komorasoft/blueprints/users/templates/users/user_exists.html
{% extends "base.html" %}
{% block title %}Uporabniki{% endblock %}

{% block content %}
<div class="card bg-dark mx-auto p-2" style="width: 18rem;">
    <center><h3>Uporabnik že obstaja!</h3></center>
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="red"  class="bi bi-ban mx-auto p-2" viewBox="0 0 16 16">
        <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
    </svg>
    <div class="card-body">
      <h5 class="card-title">Izberi drugo uporabniško ime.</h5>
      <p class="card-text">Uporabnik z izbranim imenom že obstaja, ustvarite si račun z drugačnim uporabniškim imenom.</p>
      <a href="{{url_for('users.index')}}" class="btn btn-primary">Nazaj</a>
    </div>
  </div>
{% endblock %}