komorasoft/blueprints/actuators/models.py
from komorasoft.app import db
from sqlalchemy import UniqueConstraint
from datetime import datetime, timedelta
import asyncio
import logging


class Actuator(db.Model):
    __tablename__ = 'aktuatorji'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String, nullable=False)
    description = db.Column(db.String)
    interval = db.Column(db.Interval, default=timedelta(seconds=0), nullable=False)
    duration = db.Column(db.Interval, default=timedelta(seconds=0), nullable=False)
    is_active = db.Column(db.Boolean, default=False)
    last_activation_time = db.Column(db.DateTime, nullable=True)
    last_deactivation_time = db.Column(db.DateTime, nullable=True)

    __table_args__ = (
        UniqueConstraint('name', name='uq_name'),
    )
    

    def __repr__(self):
        return f"{self.name}, stanje:    {self.is_active},   opis:    {self.description}"
    
    def get_id(self):
        return self.id
    
# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# async def control_actuator(actuator):
#     now = datetime.now()
    
#     try:
#         # Calculate activation and deactivation times
#         next_activation_time = actuator.last_activation_time + actuator.interval if actuator.last_activation_time else now + actuator.interval
#         next_deactivation_time = actuator.last_activation_time + actuator.duration if actuator.last_activation_time else next_activation_time + actuator.duration

#         # Activation logic
#         if now >= next_activation_time and not actuator.is_active:
#             logger.info(f"Activating {actuator.name} at {now}")
#             actuator.is_active = True
#             actuator.last_activation_time = now
#             db.session.commit()

#         # Deactivation logic
#         if now >= next_deactivation_time and actuator.is_active:
#             logger.info(f"Deactivating {actuator.name} at {now}")
#             actuator.is_active = False
#             actuator.last_deactivation_time = now
#             db.session.commit()

#     except Exception as e:
#         logger.error(f"Error in controlling actuator {actuator.name}: {e}")
#         db.session.rollback()  # Rollback the transaction on error
#         # Implement retry logic if necessary
        

komorasoft/blueprints/actuators/routes.py
from flask import request, render_template, redirect, url_for, Blueprint
from flask_login import current_user, login_required

from komorasoft.app import db
from komorasoft.blueprints.actuators.models import Actuator

actuators = Blueprint('actuators', __name__, static_folder='static', template_folder='templates')


@actuators.route('/')
def index():
    actuators = Actuator.query.all()
    #cols = [column.name for column in Actuator.__table__.columns]
    cols = ["ID","Naziv","Stanje","Opis","Dejanja"]
    rows = [[actuator.id,actuator.name,actuator.is_active,actuator.description] for actuator in actuators]
    return render_template('actuators/index.html', actuators=actuators, columns=cols, rows=rows)

@actuators.route('/create', methods=['GET','POST'])
@login_required
def create():
    if request.method == 'GET':
        return render_template('actuators/create.html')
    elif request.method == 'POST':
        name = request.form.get('naziv')
        desc = request.form.get('description')
        desc = desc if desc != '' else None # dodaj opis, če ga je uporabnik definiral
        is_active = False # preveri dejansko stanje aktuatorja!

        existing_actuators = Actuator.query.all() # get all sensors
        actuator_names = [actuator.name for actuator in existing_actuators] # get all sensor names

        if name not in actuator_names:
            actuator = Actuator(name=name, description=desc, is_active=is_active) # dodaj nov aktuator

            db.session.add(actuator)
            db.session.commit()

            return redirect(url_for('actuators.index'))
        else:
            return render_template('actuators/actuator_exists.html')
    
@actuators.route('/delete', methods=['GET','POST'])
@login_required
def delete():
    if request.method == 'GET':
        actuators = Actuator.query.all()
        return render_template('actuators/delete.html', actuators=actuators)
    elif request.method == 'POST':
        name = request.form.get('naziv')

        actuator = Actuator.query.filter(Actuator.name == name).first()

        if current_user.is_authenticated and current_user.role == "Administrator":
            db.session.delete(actuator)
            db.session.commit()
            return redirect(url_for('actuators.index'))
        else:
            return render_template('actuators/not_authorized.html')
        

@actuators.route('/edit', methods=['GET','POST'])
@login_required
def edit():
    if request.method == 'GET':
        return render_template('actuators/edit.html')
    elif request.method == 'POST':
        name_old = request.form.get('name_old')
        name = request.form.get('name')
        desc = request.form.get('description')
        desc = desc if desc != '' else None # dodaj opis, če ga je uporabnik definiral
        is_active = False # preveri dejansko stanje aktuatorja!

        actuator = Actuator.query.filter(Actuator.name == name_old).first()

        if current_user.is_authenticated and current_user.role=="Administrator":
            actuator.name = name
            actuator.description = desc
            actuator.is_active = is_active
            db.session.commit()  # Commit the changes to the database
            return redirect(url_for('actuators.index'))
        else:
            return render_template('actuators/not_authorized.html')

komorasoft/blueprints/actuators/templates/actuators/actuator_exists.html
{% extends "base.html" %}
{% block title %}Aktuatorji{% endblock %}

{% block content %}
<div class="card bg-dark mx-auto p-2" style="width: 18rem;">
    <center><h3>Aktuator že obstaja!</h3></center>
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="red"  class="bi bi-ban mx-auto p-2" viewBox="0 0 16 16">
        <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
    </svg>
    <div class="card-body">
      <h5 class="card-title">Dodaj aktuator z drugačnim imenom.</h5>
      <p class="card-text">Aktuator z izbranim imenom že obstaja, novega lahko ustvarite tako, da mu dodelite drugačno ime.</p>
      <a href="{{url_for('actuators.index')}}" class="btn btn-primary">Nazaj</a>
    </div>
  </div>
{% endblock %}

komorasoft/blueprints/actuators/templates/actuators/create.html
{% extends "base.html" %}
{% block title %}Aktuatorji{% endblock %}

{% block content %}
    <h1>Dodaj aktuator</h1>
    <form action="{{url_for('actuators.create')}}" method="POST">
        <input type="text" name="naziv" placeholder="Naziv" required="required">
        <input type="text" name="description" placeholder="Opis">
        <input type="submit" value="Dodaj">
    </form>
{% endblock %}

komorasoft/blueprints/actuators/templates/actuators/delete.html
{% extends "base.html" %}
{% block title %}Aktuatorji{% endblock %}

{% block content %}
    <h1>Odstrani aktuator</h1>
    <ul>
        {% for actuator in actuators %}
            <li>{{actuator}}</li>
        {% endfor %}
    </ul><br>
    <form action="{{url_for('actuators.delete')}}" method="POST">
        <input type="text" name="naziv" placeholder="Naziv" required="required">
        <input type="submit" value="Odstrani">
    </form>
{% endblock %}

komorasoft/blueprints/actuators/templates/actuators/edit.html
<!-- Modal -->
<div class="modal fade" id="modalEdit{{ loop.index }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalLabel{{ loop.index }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel{{ loop.index }}">Uredi aktuator</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Želiš spremeniti aktuator:    <b>{{ row[1] }}</b>?</p>
            </div>
            <div class="container" align="center">
                <form action="{{ url_for('actuators.edit') }}" method="post">
                    <input name="name_old" placeholder="{{ row[1] }}" value="{{row[1]}}" hidden>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1" style="width: 100px;">Naziv</span>
                        <input type="text" class="form-control" id="input_name" name="name" placeholder="{{ row[1] }}" value="{{ row[1] }}" required="required" aria-label="{{ row[1] }}" aria-describedby="basic-addon1">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1" style="width: 100px;">Opis</span>
                        <input type="text" class="form-control" id="desc" name="description" placeholder="{{ row[3] }}" value="{{ row[3] }}" aria-label="{{ row[3] }}" aria-describedby="basic-addon1">
                    </div>
                    <!-- <input id="input_name" name="name" placeholder="{{ row[1] }}" required="required"><br> -->
                    <!-- <input id="desc" name="description" placeholder="{{ row[3] }}"> -->
                    <button type="submit" class="btn btn-primary">OK</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button><br><br>
                </form>
                
            </div>
        </div>
    </div>
</div>

komorasoft/blueprints/actuators/templates/actuators/index.html
{% extends "base.html" %}
{% block title %}Aktuatorji{% endblock %}

{% block content %}
<div>
    <h1>AKTUATORJI</h1><br>
    
    {% if actuators %}
        <table class="table table-success table-hover">
            <thead>
                <tr>
                    {% for col in columns %}
                        <th scope="col">{{col}}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        {% for element in row %}
                            <td>{{element}}</td>
                        {% endfor %}
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalEdit{{ loop.index }}">Uredi</button>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalDelete{{ loop.index }}">
                                    Odstrani
                                </button>
                            </div>

                            {% include 'actuators/edit.html'%}
                            {% include 'actuators/remove.html'%}
                            
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <center><p>V bazi ni shranjen noben aktuator.</p></center>
    {% endif %}
</div><br>
{% if current_user.role == "Administrator" %}
<div align="right">
    <form action="{{ url_for('actuators.create') }}" method="post">
        <input class="align-middle" type="text" name="naziv" placeholder="Naziv" required="required" style="height: 38px;">
        <input class="align-middle" type="text" name="description" placeholder="Opis" style="height: 38px;">
        <button type="submit" class="btn btn-dark align-middle" style="height: 40px;">Dodaj aktuator</button>
    </form>
</div>
{% endif %}
<div>
    <br>
    <br>
</div>
{% endblock %}

komorasoft/blueprints/actuators/templates/actuators/not_authorized.html
{% extends "base.html" %}
{% block title %}Aktuatorji{% endblock %}

{% block content %}
<div class="card bg-dark mx-auto p-2" style="width: 18rem;">
    <center><h3>Nisi pooblaščen!</h3></center>
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="red"  class="bi bi-ban mx-auto p-2" viewBox="0 0 16 16">
        <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
    </svg>
    <div class="card-body">
      <h5 class="card-title">Žal nimaš dovoljenj!</h5>
      <p class="card-text">Tega dejanja ne moreš izvesti, saj nimaš ustreznih pravic. Za več info kontaktiraj administratorja.</p>
      <a href="{{url_for('actuators.index')}}" class="btn btn-primary">Nazaj</a>
    </div>
  </div>
{% endblock %}

komorasoft/blueprints/actuators/templates/actuators/remove.html
<!-- Modal -->
<div class="modal fade" id="modalDelete{{ loop.index }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="modalLabel{{ loop.index }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="modalLabel{{ loop.index }}">Odstrani aktuator</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Želiš trajno izbrisati aktuator: {{ row[1] }}?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                <form action="{{ url_for('actuators.delete') }}" method="post">
                    <input type="hidden" name="naziv" value="{{ row[1] }}">
                    <button type="submit" class="btn btn-primary">OK</button>
                </form>
            </div>
        </div>
    </div>
</div>