komorasoft/blueprints/core/routes.py
from flask import render_template, Blueprint

from komorasoft.app import db

core = Blueprint('core', __name__, static_folder='static', template_folder='templates')

@core.route('/')
def index():
    return render_template('core/index.html')

@core.route('/not_authorized')
def not_authorized():
    return render_template('core/not_authorized.html')

komorasoft/blueprints/manual/routes.py
from flask import request, render_template, redirect, url_for, Blueprint, jsonify
from flask_login import current_user, login_required

from komorasoft.app import db
from komorasoft.blueprints.actuators.models import Actuator
from komorasoft.blueprints.simple.models import Settings

manual = Blueprint('manual', __name__, static_folder='static', static_url_path='/static', template_folder='templates')


@manual.route('/')
@login_required
def index():
    active_setting = Settings.query.filter_by(active=True).first() # find active setting
    if active_setting:
        return render_template('manual/setting_active.html')
    else:
        if current_user.role == "Administrator":
            actuators = Actuator.query.all()  # Fetch all actuators from the database
            return render_template('manual/index.html', actuators=actuators)
        else:
            return render_template('manual/not_authorized.html')
        

@manual.route('/toggle_device', methods=['POST'])
def toggle_device():
    data = request.get_json()
    device_id = data.get('device_id')
    if device_id is None:
        return jsonify({'error': 'No device_id provided'}), 400

    # Find the actuator by its ID
    actuator = Actuator.query.get(device_id)
    if actuator is None:
        return jsonify({'error': 'Actuator not found'}), 404

    # Toggle the state
    actuator.is_active = not actuator.is_active

    # Commit the changes to the database
    db.session.commit()

    # Return the new state as a response
    return jsonify({'new_state': actuator.is_active})
    
    

komorasoft/blueprints/simple/routes.py
from flask import request, render_template, redirect, url_for, Blueprint, jsonify
from flask_login import current_user, login_required
import json
from datetime import datetime, timedelta

from komorasoft.app import db
from komorasoft.blueprints.actuators.models import Actuator
from komorasoft.blueprints.simple.models import Settings, ActuatorSetting
from komorasoft.scripts.frontend.updateui import update_active_setting, check_active, stop_all, stop_all_settings

simple = Blueprint('simple', __name__, static_folder="static", template_folder='templates/simple')


def serialize_actuator(actuator):
    return {
        'id': actuator.id,
        'name': actuator.name,
        'description': actuator.description,
        # Add other fields as needed
    }

@simple.route('/')
@login_required
def index():
    if current_user.role == "Administrator":
        actuators = Actuator.query.filter(~Actuator.name.in_(["Kompresor","Ventilator uparjalnika","Grelec uparjalnika","Vlažilnik"])).all() # get all user controlable actuators
        ser_actuators = [serialize_actuator(actuator) for actuator in actuators]
        ptc_actuators = Actuator.query.filter(Actuator.name.in_(["Ventilator uparjalnika","Grelec uparjalnika","Vlažilnik"])).all() # get all potencial user controlable actuators
        ser_ptc_actuators = [serialize_actuator(actuator) for actuator in ptc_actuators]
        return render_template('index.html', actuators=ser_actuators, ptc_actuators=ser_ptc_actuators)
    else:
        return render_template('not_authorized.html')
    

@simple.route('/save_settings', methods=['POST'])
@login_required
def save_settings():

    # Function that check if a set interval is longer than a duration
    def checkIntervalVSDuration(intDays,intHours,intMinutes,intSeconds,DurHours,DurMinutes,DurSeconds):
        interval_length = timedelta(days=int(intDays),hours=int(intHours),minutes=int(intMinutes),seconds=int(intSeconds))
        duration_length = timedelta(hours=int(DurHours),minutes=int(DurMinutes),seconds=int(DurSeconds))
        print(f"Interval: {interval_length}, Duration: {duration_length}, Comparrison: {interval_length >= duration_length}")
        return interval_length, duration_length
    
    # Function that inserts user inputs to the database for every actuator setting
    def settings2db(settings_obj, data, advanced, exists):
        if not exists:
            # Create new settings for every acutator
            for actuator, actuator_settings in data.items(): # for each actuator, read data for interval and duration
                usr_control = True if advanced else False
                if actuator not in ["settingsID","advancedCheck","settingsDescription","settingsTitle","temperatureRange"]:
                    IntDays = actuator_settings[actuator+'IntDays']
                    IntHours = actuator_settings[actuator+'IntHours']
                    IntMinutes = actuator_settings[actuator+'IntMinutes']
                    IntSeconds = actuator_settings[actuator+'IntSeconds']
                    DurHours = actuator_settings[actuator+'DurHours']
                    DurMinutes = actuator_settings[actuator+'DurMinutes']
                    DurSeconds = actuator_settings[actuator+'DurSeconds']

                    interval_length, duration_length = checkIntervalVSDuration(IntDays,IntHours,IntMinutes,IntSeconds,DurHours,DurMinutes,DurSeconds)
                    if (interval_length > duration_length) or (interval_length == duration_length == timedelta(seconds=0)):
                        newActuatorSetting = ActuatorSetting(name=actuator,
                                                            user_control=usr_control,
                                                            IntDays=IntDays,
                                                            IntHours=IntHours,
                                                            IntMinutes=IntMinutes,
                                                            IntSeconds=IntSeconds,
                                                            DurHours=DurHours,
                                                            DurMinutes=DurMinutes,
                                                            DurSeconds=DurSeconds,
                                                            settings_id=settings_obj.id)
                        print("test 2.1")
                        db.session.add(newActuatorSetting)
                        db.session.commit()
                        print("test 2.2")
                        print(f"Created. Added the acutator's settings: {actuator, usr_control,IntDays,IntHours,IntMinutes,IntSeconds,settings_obj.id}")
                    else:
                        print(f'The interval is shorter than the duration at actuator setting: {actuator}')
                        return jsonify({'message': f'The interval is shorter than the duration at {actuator} setting'})
        else:
            # Find and update the existing setting for every actuator
            for actuator, actuator_settings in data.items(): # for each actuator, read data for interval and duration
                usr_control = True if advanced else False
                if actuator not in ["settingsID","advancedCheck","settingsDescription","settingsTitle","temperatureRange"]:
                    print(f"Nastavitev: {actuator}")
                    editActuatorSetting = ActuatorSetting.query.filter_by(name=actuator, settings_id=settings_obj.id).first()
                    print(f"Stevilo act nastavitev {len(ActuatorSetting.query.filter_by(name=actuator, settings_id=settings_obj.id).all())}")
                    print(editActuatorSetting)
                    print(editActuatorSetting.id)

                    IntDays = actuator_settings[actuator+'IntDays']
                    IntHours = actuator_settings[actuator+'IntHours']
                    IntMinutes = actuator_settings[actuator+'IntMinutes']
                    IntSeconds = actuator_settings[actuator+'IntSeconds']
                    DurHours = actuator_settings[actuator+'DurHours']
                    DurMinutes = actuator_settings[actuator+'DurMinutes']
                    DurSeconds = actuator_settings[actuator+'DurSeconds']

                    interval_length, duration_length = checkIntervalVSDuration(IntDays,IntHours,IntMinutes,IntSeconds,DurHours,DurMinutes,DurSeconds)
                    if (interval_length > duration_length) or (interval_length == duration_length == timedelta(seconds=0)):
                        editActuatorSetting.user_control = usr_control
                        editActuatorSetting.IntDays = IntDays
                        editActuatorSetting.IntHours = IntHours
                        editActuatorSetting.IntMinutes = IntMinutes
                        editActuatorSetting.IntSeconds = IntSeconds
                        editActuatorSetting.DurHours = DurHours
                        editActuatorSetting.DurMinutes = DurMinutes
                        editActuatorSetting.DurSeconds = DurSeconds
                        editActuatorSetting.settings_id = settings_obj.id
                    
                        db.session.commit()
                        print(f"Edited. Changed the acutator's settings: {actuator, usr_control,IntDays,IntHours,IntMinutes,IntSeconds,settings_obj.id}")
                    else:
                        return jsonify({'message': f'The interval is shorter than the duration at actuator setting: {actuator}'})

    if current_user.role == "Administrator":
        data = request.json # get data from JS
        settingsID = data['settingsID']['settingsID'] # setting's ID
        name = data['settingsTitle']['settingsTitle'] # user defined or selected settings Title
        description = data['settingsDescription']['settingsDescription'] if data['settingsDescription']['settingsDescription'] != "" else "Brez opisa." # user defined or selected settings description
        temperature = data['temperatureRange']['temperatureRange'] # user defined temperature [Int]
        advanced = data['advancedCheck']['advancedCheck'] # check if user defined advanced settings [True/False]
        
        existingSettings = Settings.query.filter_by(id=settingsID, name=name).first()
        print(f"Submitted data: {data}")
        if existingSettings: # assign the new values = overwrite the Settings
            print(f"Editing. Name: {name}")
            # Edit the Settings
            existingSettings.description = description # update description
            existingSettings.temperature = temperature # update temperature
            existingSettings.advanced = advanced # update advanced
            db.session.commit()
            # set the rest of the parameters
            settings2db(existingSettings, data, advanced, True)
            return jsonify("Edited settings",data), 201
        else:
            print(f"Creating. Name: {name}, ID: {settingsID}")
            # Create new Settings
            newSettings = Settings(name=name,description=description,advanced=advanced,temperature=temperature)
            db.session.add(newSettings)
            db.session.commit()
            # set the rest of the parameters
            settings2db(newSettings, data, advanced, False)
            return jsonify("Created new settings",data), 201
    else:
        return render_template('not_authorized.html')
    


@simple.route('/get_settings', methods=['GET'])
def get_settings():
    settings = Settings.query.all()
    settings_data = [{'id': setting.id, 
                      'name': setting.name, 
                      'description':setting.description, 
                      'created':setting.created} for setting in settings]
    return jsonify(settings_data)

@simple.route('/get_setting/<string:setting_id>', methods=['GET'])
def get_setting(setting_id):
    # Fetch the setting from the database
    setting = Settings.query.get(setting_id)
    advanced = setting.advanced

komorasoft/blueprints/users/routes.py
from flask import request, render_template, redirect, url_for, Blueprint
from komorasoft.blueprints.users.models import User

from flask_login import login_user, logout_user, current_user, login_required

users = Blueprint('users', __name__, template_folder='templates')


def register_user_routes(app, db, bcrypt):
    @users.route('/')
    def index():
        users = User.query.all()
        if current_user.is_authenticated:
            return render_template('users/index.html', users=users, current_user=current_user)
        else:
            return render_template('users/index.html', users=users, current_user=None)


    @users.route('/signup', methods=['GET', 'POST'])
    def signup():
        if request.method == 'GET':
            return render_template('users/signup.html')
        elif request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            role = request.form.get('role')
            desc = request.form.get('description')
            desc = desc if desc != '' else None # if defined, add description

            # Check if user already exists
            existing_users = User.query.all()
            existing_usernames = [user.username for user in existing_users]

            if username not in existing_usernames:
                hashed_password = bcrypt.generate_password_hash(password) # store only hash of the passwd into the database

                user = User(username=username, password=hashed_password, role=role, description=desc) # add new user

                db.session.add(user)
                db.session.commit()
                return redirect(url_for('users.index'))
            else:
                return render_template('users/user_exists.html')


    @users.route('/login', methods=['GET', 'POST'])
    def login():
        if request.method == 'GET':
            return render_template('users/login.html')
        elif request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            next = request.form.get('next') # which page did the user login from

            user = User.query.filter(User.username == username).first()

            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                return redirect(next)
            else:
                return 'Neuspešen vpis'
            
    @users.route('/delete', methods=['GET', 'POST'])
    @login_required
    def delete():
        if request.method == 'GET':
            users = User.query.all()
            return render_template('users/delete.html', users=users)
        elif request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')

            user = User.query.filter(User.username == username).first()

            if bcrypt.check_password_hash(user.password, password) and current_user.role == "Administrator":
                db.session.delete(user)
                db.session.commit()
                return redirect(url_for('users.index'))
            else:
                return render_template('users/not_authorized.html')

    @users.route('/logout', methods=['GET','POST'])
    def logout():
        if request.method == 'POST':
            next = request.form.get('next')
            logout_user()
            return redirect(next)
        else:
            return redirect(next)
    

komorasoft/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>KomoraSOFT</title>
    
    
    <!-- Link to other css files (Bootstrap) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.3/font/bootstrap-icons.min.css">

    <!-- Link to the CSS file -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <!-- AUTO Link to the CSS file -->
    
    
  </head>
  <body>
    
    {% include 'navbar.html' %}
    <br/>
    <div id="main-container" class="container-xl">
        {% block content %}
        
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
        
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.0/socket.io.js"></script> <!-- for web-sockets -->
    <script src="{{ url_for('static', filename='js/gui_sockets.js') }}"></script>
    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
    <script src="{{ url_for('static', filename='js/socket_toggle_actuators.js') }}"></script>
  </body>
</html>

komorasoft/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('core.index')}}">KomoraSOFT</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('core.index')}}">Prikazovalnik</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Upravljanje
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('simple.index')}}">Enostavno</a></li>
              <li><a class="dropdown-item" href="{{url_for('manual.index')}}">Ročno</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Naprave
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('sensors.index')}}">Senzorji</a></li>
              <li><a class="dropdown-item" href="{{url_for('actuators.index')}}">Aktuatorji</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Meritve</a>
          </li>
          
        </ul>
        <div class="container-fluid d-flex justify-content-center align-items-center">
          <p id="sensorsIndicatorText" style="width: fit-content; margin: 0%; padding: 0%;">Beleženje SENZORJEV</p>
          <img id="sensorsIndicator" src="{{url_for('static',filename='images/sensors-black.png')}}" alt="senzorji" style="height: 25px; margin-left: 20px;">
          <p id="programIndicatorText" style="width: fit-content; margin: 0%; padding: 0%; margin-left: 60px;">Izvajanje programa</p>
          <img id="programIndicator" src="#" alt="program aktiven?" style="height: 25px; margin-left: 20px;">
          <p id="tempIndicatorText" style="width: fit-content; margin: 0%; padding: 0%; margin-left: 50px;">T=x˚C</p>
        </div>
        {% if not current_user.is_authenticated %}
          <form action="{{url_for('users.login')}}" class="d-flex" role="search" method="POST">
            <input type="hidden" name="next" value="{{ request.url }}">
            <input class="form-control me-2" type="text" name="username" required="required" placeholder="Uporabnik" aria-label="Search">
            <input class="form-control me-2" type="password" name="password" placeholder="Geslo" id="geslo" required="required" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Vpis</button>
          </form>
        {% else %}
          <form action="{{url_for('users.logout')}}" method="POST">
            <input type="hidden" name="next" value="{{ request.url }}">
            <div class="btn-group">
            <a href="{{url_for('users.index')}}" class="btn btn-success">{{current_user.username}}</a>
            <button type="submit" class="btn btn-dark">Izpis</button>
            </div>
          </form>
        {% endif %}
      </div>
    </div>
  </nav>