komorasoft/blueprints/auto/routes.py
from flask import request, jsonify, render_template, redirect, url_for, Blueprint
from flask_login import current_user, login_required
from komorasoft.app import db
from komorasoft.blueprints.auto.models import Schedule, ActuatorEvent
from komorasoft.blueprints.actuators.models import Actuator
from datetime import datetime, timedelta
from typing import List, Optional

auto = Blueprint('auto', __name__, static_folder='static', template_folder='templates')

@auto.route('/')
def index():
    return render_template('auto/index.html')

@auto.route('/add_schedule', methods=['POST'])
@login_required
def add_schedule():
    # try:
    #     data = request.get_json()
    #     name = data.get('name', 'protokol')
    #     description = data.get('description', 'najboljši protokol')
    #     start_time = datetime.fromisoformat(data.get('start_time', datetime.now().isoformat()))
    # except:
    name = request.form.get('name')
    description = request.form.get('description')
    start_time = request.form.get('start_time')
    start_time = datetime.strptime(start_time, '%Y-%m-%dT%H:%M')
    existing_schedule = Schedule.query.filter_by(name=name).first()
    if existing_schedule:
        return render_template('auto/schedule_exists.html')
    else:
        schedule = Schedule(name=name, description=description, start_time=start_time)
        db.session.add(schedule)
        db.session.commit()
        return render_template('auto/index.html')

@auto.route('/edit_schedule', methods=['POST'])
@login_required
def edit_schedule():
    schedule_id = request.form.get('schedule_id')
    name = request.form.get('name')
    description = request.form.get('description')
    start_time = request.form.get('start_time')
    start_time = datetime.strptime(start_time, '%Y-%m-%dT%H:%M')
    print(name,start_time)

    schedule = Schedule.query.filter(Schedule.schedule_id == schedule_id).first()
    schedule.name = name
    schedule.description = description
    schedule.start_time = start_time
    db.session.commit()
    return render_template('auto/index.html')

@auto.route('/remove_schedule', methods=['POST'])
@login_required
def remove_schedule():
    schedule_id = request.form.get('schedule_id')
    print(schedule_id)
    schedule = Schedule.query.filter_by(schedule_id=schedule_id).first()
    print(schedule)
    db.session.delete(schedule)
    db.session.commit()
    return render_template('auto/index.html')

@auto.route('/get_schedule/<schedule_id>', methods=['GET'])
def get_schedule(schedule_id):
    schedule = Schedule.query.filter_by(schedule_id=schedule_id).first()
    if schedule:
        return jsonify({
            'schedule_id': schedule.schedule_id,
            'name': schedule.name,
            'description': schedule.description,
            'start_time': schedule.start_time.isoformat()  # Use ISO format for datetime
        })
    return jsonify({'error': 'Schedule not found'}), 404


@auto.route('/add_event', methods=['POST'])
@login_required
def add_event():
    actuator_name = request.form.get('izbran_aktuator')
    state = True if request.form.get('status_aktuatorja')=="on" else False
    dnevi = request.form.get('dni')
    ure = request.form.get('ur')
    minute = request.form.get('minut')
    sekunde = request.form.get('sekund')
    offset = timedelta(days=int(dnevi),hours=int(ure),minutes=int(minute),seconds=int(sekunde))
    schedule_id = request.form.get('createEventScheduleId')

    existing_schedule = Schedule.query.filter_by(schedule_id=schedule_id).first() 
    existing_actuator = Actuator.query.filter_by(name=actuator_name).first() 
    if existing_schedule: # check if Schedule exists
        if existing_actuator: # check if Actuator exists
            existing_event = ActuatorEvent.query.filter_by(actuator_name=actuator_name, offset=offset, schedule_id=schedule_id).first() # check if event exists
            if existing_event:
                print('Event in the selected schedule already exists!')
                return render_template('/auto/event_exists.html')
            else:
                event = ActuatorEvent(actuator_name=actuator_name, state=state, offset=offset, schedule_id=schedule_id) # create a new event for this actuator and schedule
                db.session.add(event)
                db.session.commit()
                return render_template('/auto/index.html')
        else:
            return jsonify({'message': f'No actuator: {actuator_name} found!'}), 404
    else:
        return jsonify({'message': f'No schedule with the ID: {schedule_id} found!'}), 404

@auto.route('/remove_event', methods=['POST'])
@login_required
def remove_event():
    event_id = request.form.get('event_id')
    event = ActuatorEvent.query.filter_by(id=event_id).first()
    if event:
        db.session.delete(event)
        db.session.commit()
        return render_template('auto/index.html')
    else:
        return jsonify({'message': f'No event found with ID {event_id}'}), 404

@auto.route('/edit_event', methods=['POST'])
@login_required
def edit_event():
    event_id = request.form.get('editEventId')
    event = ActuatorEvent.query.filter_by(id=event_id).first()
    if event:
        actuator = request.form.get('izbran_aktuator')
        state = request.form.get('status_aktuatorja')
        print(state)
        state = True if request.form.get('status_aktuatorja') == "on" else False
        day = request.form.get('dniE')
        hour = request.form.get('urE')
        minute = request.form.get('minutE')
        second = request.form.get('sekundE')
        offset = timedelta(days=int(day),hours=int(hour),minutes=int(minute),seconds=int(second))
        event.actuator_name = actuator
        event.state = state
        event.offset = offset
        db.session.commit()
        return render_template('auto/index.html')
    else:
        return jsonify({'message': f'No event found with ID {event_id}'}), 404


@auto.route('/get_event/<eventId>', methods=['GET'])
def get_event(eventId):
    event = ActuatorEvent.query.filter_by(id=eventId).first()
    if event: # get total seconds
        days = event.offset.days # extract days
        additional_seconds = event.offset.seconds # extract the rest of the seconds
        hours = additional_seconds // 3600 # extract hours
        minutes = (additional_seconds % 3600) // 60
        seconds = additional_seconds % 60

        return jsonify({
            'id': event.id,
            'name': event.actuator_name,
            'offset': event.offset.total_seconds(),
            'state': event.state,
            'schedule_id': event.schedule_id,
            'days': days,
            'hours': hours,
            'minutes': minutes,
            'seconds': seconds
        })
    return jsonify({'error': 'Schedule not found'}), 404


@auto.route('/get_schedules')
def get_schedules():
    schedules = Schedule.query.all()
    return jsonify([{
        'schedule_id': schedule.schedule_id,
        'name': schedule.name,
        'description': schedule.description,
        'start_time': schedule.start_time.isoformat()
    } for schedule in schedules]), 200

@auto.route('/get_events')
def get_events():
    events = ActuatorEvent.query.all()
    return jsonify([{
        'id': event.schedule_id,
        'event_id':event.id,
        'actuator_name': event.actuator_name,
        'state': event.state,
        'offset': event.offset.total_seconds()
    } for event in events]), 200

@auto.route('/get_actuator_events', methods=['GET'])
def get_actuator_events():
    def serialize_actuator_event(event, abs_time):
        return {
            'id': event.id,
            'actuator_name': event.actuator_name,
            'state': event.state,
            'offset': event.offset.total_seconds(),
            'schedule_id': event.schedule_id,
            'absolute_time': abs_time.strftime('%Y-%m-%d %H:%M:%S')  # Format the absolute time as a string
        }

    schedule_id = request.args.get('schedule_id')
    schedule = Schedule.query.filter_by(schedule_id=schedule_id).first()
    
    if not schedule:
        return jsonify({'error': 'Schedule not found'}), 404

    events = ActuatorEvent.query.filter_by(schedule_id=schedule_id).order_by(ActuatorEvent.offset.asc()).all()
    
    events_list = []
    for event in events:
        abs_time = schedule.start_time + event.offset
        events_list.append(serialize_actuator_event(event, abs_time))

    return jsonify(events_list)

@auto.route('/get_actuators', methods=['GET'])
def get_actuators():
    actuators = Actuator.query.all()  # Assuming Actuator is your model
    return jsonify([{'sid': actuator.sid, 'name': actuator.name} for actuator in actuators])


@auto.route('/test')
def test():
    return render_template('auto/test.html')

komorasoft/blueprints/auto/templates/auto/event_create.html
<!-- Create Event Modal -->
<div class="modal fade" id="createEventModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="createEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="max-width: 60%;">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="createEventModalLabel" style="color: chartreuse;">Ustvari dogodek</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><br>
                <form id="createEventForm" action="{{url_for('auto.add_event')}}" method="POST">
                    <h5 style="color: rgb(255, 255, 255);">Aktuator</h5>
                    <input type="hidden" id="createEventScheduleId" name="createEventScheduleId">
                    <div class="row g-2">
                        <div class="col-md-8">
                            <div class="form-floating" required>
                                <select class="form-select" id="actuatorSelect" aria-label="Izberi aktuator", name="izbran_aktuator">
                                <option selected id="selectedOptionActuator">Izbran aktuator</option>
                                        <!-- JS will populate options with available actuators here -->
                                </select>
                                <label for="floatingSelect">Izberi aktuator</label>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" name="status_aktuatorja">
                                <label class="form-check-label" for="flexSwitchCheckDefault" style="color: white;">Vklop/Izklop</label>
                              </div>
                        </div>
                    </div><br><br>



                    <h5 style="color: rgb(255, 255, 255);">Čas od začetka izvajanja protokola</h5>
                    <div class="row g-2">
                        <div class="col">
                            <!-- Dnevi -->
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Dan" aria-label="Dan" aria-describedby="basic-addon2" value="0" name="dni" required>
                                <span class="input-group-text" id="dan">dni</span>
                            </div>
                        </div>
                        <div class="col">
                            <!-- Ure -->
                            <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Ura" aria-label="Ura" aria-describedby="basic-addon2" value="0" name="ur" required>
                            <span class="input-group-text" id="basic-addon2">ur</span>
                            </div>
                        </div>
                        <div class="col">
                            <!-- Minute -->
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Minuta" aria-label="Minuta" aria-describedby="basic-addon2" value="0" name="minut" required>
                                <span class="input-group-text" id="basic-addon2">minut</span>
                            </div>
                        </div>
                        <div class="col">
                            <!-- Sekunde -->
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Sekunda" aria-label="Sekunda" aria-describedby="basic-addon2" value="0" name="sekund" required>
                                <span class="input-group-text" id="basic-addon2">sekund</span>
                            </div>
                        </div>
                    </div>

                    <div align="right">
                        <button type="submit" class="btn btn-primary">Potrdi</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', () => {
    // Function to fetch actuators and populate the select element
    function populateActuators() {
        fetch('/auto/get_actuators', { method: 'GET' })
            .then(response => response.json())
            .then(data => {
                const actuatorSelect = document.getElementById('actuatorSelect');
                actuatorSelect.innerHTML = '<option selected="false"> </option>';  // Clear existing options

                data.forEach(actuator => {
                    const option = document.createElement('option');
                    option.value = actuator.name;
                    option.textContent = actuator.name;
                    actuatorSelect.appendChild(option);
                });
            })
            .catch(error => console.error('Error loading actuators:', error));
    }

    // Event listener to populate actuators when the modal is shown
    const createEventModal = document.getElementById('createEventModal');
    createEventModal.addEventListener('show.bs.modal', populateActuators);
});
</script>
    

komorasoft/blueprints/auto/templates/auto/event_edit.html
<!-- edit Event Modal -->
<div class="modal fade" id="editEventModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="editEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="max-width: 60%;">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="editEventModalLabel" style="color: chartreuse;">Uredi dogodek</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><br>
                <form id="editEventForm" action="{{url_for('auto.edit_event')}}" method="POST">
                    <h5 style="color: rgb(255, 255, 255);">Aktuator</h5>
                    <input type="hidden" id="editEventId" name="editEventId">
                    <div class="row g-2">
                        <div class="col-md-8">
                            <div class="form-floating" required>
                                <select class="form-select" id="actuatorSelectEdit" aria-label="Izberi aktuator", name="izbran_aktuator">
                                <option selected id="selectedOptionActuator">Izbran aktuator</option>
                                        <!-- JS will populate options with available actuators here -->
                                </select>
                                <label for="floatingSelect">Izberi aktuator</label>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-check form-switch">
                                <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault2" name="status_aktuatorja">
                                <label class="form-check-label" for="flexSwitchCheckDefault2" style="color: white;">Vklop/Izklop</label>
                              </div>
                        </div>
                    </div><br><br>



                    <h5 style="color: rgb(255, 255, 255);">Čas od začetka izvajanja protokola</h5>
                    <div class="row g-2">
                        <div class="col">
                            <!-- Dnevi -->
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Dan" aria-label="Dan" aria-describedby="basic-addon2" value="0" id="dni" name="dniE" required>
                                <span class="input-group-text" id="dan">dni</span>
                            </div>
                        </div>
                        <div class="col">
                            <!-- Ure -->
                            <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Ura" aria-label="Ura" aria-describedby="basic-addon2" value="0" id="ur" name="urE" required>
                            <span class="input-group-text" id="basic-addon2">ur</span>
                            </div>
                        </div>
                        <div class="col">
                            <!-- Minute -->
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Minuta" aria-label="Minuta" aria-describedby="basic-addon2" value="0" id="minut" name="minutE" required>
                                <span class="input-group-text" id="basic-addon2">minut</span>
                            </div>
                        </div>
                        <div class="col">
                            <!-- Sekunde -->
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="Sekunda" aria-label="Sekunda" aria-describedby="basic-addon2" value="0" id="sekund" name="sekundE" required>
                                <span class="input-group-text" id="basic-addon2">sekund</span>
                            </div>
                        </div>
                    </div>

                    <div align="right">
                        <button type="submit" class="btn btn-primary">Potrdi</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', () => {
    // Function to fetch actuators and populate the select element
    function populateActuators() {
        fetch('/auto/get_actuators', { method: 'GET' })
            .then(response => response.json())
            .then(data => {
                const actuatorSelectEdit = document.getElementById('actuatorSelectEdit');
                actuatorSelectEdit.innerHTML = '<option selected="false"> </option>';  // Clear existing options

                data.forEach(actuator => {
                    const option = document.createElement('option');
                    option.value = actuator.name;
                    option.textContent = actuator.name;
                    actuatorSelectEdit.appendChild(option);
                });
            })
            .catch(error => console.error('Error loading actuators:', error));
    }

    // Event listener to populate actuators when the modal is shown
    const editEventModal = document.getElementById('editEventModal');
    editEventModal.addEventListener('show.bs.modal', populateActuators);
});
</script>
    

komorasoft/blueprints/auto/templates/auto/event_exists.html
{% extends "base.html" %}
{% block title %}Dogodki aktuatorjev{% endblock %}

{% block content %}
<div class="card bg-dark mx-auto p-2" style="width: 18rem;">
    <center><h3>Dogodek že obstaja!</h3></center>
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="red"  class="bi bi-ban mx-auto p-2" viewBox="0 0 16 16">
        <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
    </svg>
    <div class="card-body">
      <h5 class="card-title">Dodaj nov dogodek.</h5>
      <p class="card-text">Dogodek s temi nastavitvami že obstaja, novega lahko ustvarite tako, da mu dodelite druge parametre.</p>
      <a href="{{url_for('auto.index')}}" class="btn btn-primary">Nazaj</a>
    </div>
  </div>
{% endblock %}

komorasoft/blueprints/auto/templates/auto/event_remove.html
<!-- remove Event Modal -->
<div class="modal fade" id="removeEventModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="removeEventModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="removeEventModalLabel" style="color: chartreuse;">Izbriši dogodek</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><br>
                <p id="eventDeleteMessage">Ste prepričani, da želite izbrisati ta dogodek?</p>
                <form id="removeEventForm" action="{{url_for('auto.remove_event')}}" method="POST">
                    <input id="removeEventId" name="event_id" hidden>
                    <div align="right">
                        <button type="submit" class="btn btn-primary">Potrdi</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

komorasoft/blueprints/auto/templates/auto/execution.html
<div class="container-fluid create-schedule">
    <h1 class="glavni-naslov">Zagon</h1>
    
</div>

komorasoft/blueprints/auto/templates/auto/schedule_create.html
<!-- Create Schedule Modal -->
<div class="modal fade" id="createScheduleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="createScheduleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="createScheduleModalLabel" style="color: chartreuse;">Ustvari protokol</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><br>
                <form id="createScheduleForm" action="{{url_for('auto.add_schedule')}}" method="POST">
                    <input type="hidden" id="createScheduleId">
                    <div class="input-group mb-3">
                        <span class="input-group-text bg-success-subtle" id="basic-addon1" style="width: 100px;">Naziv</span>
                        <input type="text" class="form-control" placeholder="Naziv protokola" aria-label="Naziv protokola" aria-describedby="basic-addon1" id="name" name="name" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text bg-success-subtle" style="width: 100px;">Opis</span>
                        <input type="text" class="form-control" placeholder="Opiši protokol" aria-label="Opiši protokol" aria-describedby="basic-addon1" id="createScheduleDescription" name="description">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text bg-success-subtle" style="width: 100px;">Čas začetka</span>
                        <input type="datetime-local" class="form-control" placeholder="Čas začetka" aria-label="Določi čas začetka" aria-describedby="basic-addon1" id="createScheduleStartTime" name="start_time">
                    </div><br>
                    <div align="right">
                        <button type="submit" class="btn btn-primary">Potrdi</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

komorasoft/blueprints/auto/templates/auto/schedule_edit.html
<!-- Edit Schedule Modal -->
<div class="modal fade" id="editScheduleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="editScheduleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="editScheduleModalLabel" style="color: chartreuse;">Uredi protokol</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><br>
                <form id="editScheduleForm" action="{{url_for('auto.edit_schedule')}}" method="POST">
                    <input id="editScheduleId" name="schedule_id" hidden>
                    <div class="input-group mb-3">
                        <span class="input-group-text bg-success-subtle" style="width: 100px;">Naziv</span>
                        <input type="text" class="form-control" placeholder="Naziv protokola" aria-label="Naziv protokola" aria-describedby="basic-addon1" id="editScheduleName" name="name" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text bg-success-subtle" style="width: 100px;">Opis</span>
                        <input type="text" class="form-control" placeholder="Opiši protokol" aria-label="Opiši protokol" aria-describedby="basic-addon1" id="editScheduleDescription" name="description" required>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text bg-success-subtle" style="width: 100px;">Čas začetka</span>
                        <input type="datetime-local" class="form-control" placeholder="Čas začetka" aria-label="Določi čas začetka" aria-describedby="basic-addon1" id="editScheduleStartTime" name="start_time" required>
                    </div><br>
                    <div align="right">
                        <button type="submit" class="btn btn-primary" id="confirmScheduleEdit">Potrdi</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

komorasoft/blueprints/auto/templates/auto/schedule_exists.html
{% extends "base.html" %}
{% block title %}Protokoli{% endblock %}

{% block content %}
<div class="card bg-dark mx-auto p-2" style="width: 18rem;">
    <center><h3>Protokol že obstaja!</h3></center>
    <svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="red"  class="bi bi-ban mx-auto p-2" viewBox="0 0 16 16">
        <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
    </svg>
    <div class="card-body">
      <h5 class="card-title">Dodaj protokol z drugačnim imenom.</h5>
      <p class="card-text">Protokol z izbranim imenom že obstaja, novega lahko ustvarite tako, da mu dodelite drugačno ime.</p>
      <a href="{{url_for('auto.index')}}" class="btn btn-primary">Nazaj</a>
    </div>
  </div>
{% endblock %}

komorasoft/blueprints/auto/templates/auto/schedule_remove.html
<!-- remove Schedule Modal -->
<div class="modal fade" id="removeScheduleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="editScheduleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title fs-5" id="removeScheduleModalLabel" style="color: chartreuse;">Izbriši protokol</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body"><br>
                <p id="scheduleDeleteMessage">Ste prepričani, da želite izbrisati ta protokol?</p>
                <form id="removeScheduleForm" action="{{url_for('auto.remove_schedule')}}" method="POST">
                    <input id="removeScheduleId" name="schedule_id" hidden>
                    <div align="right">
                        <button type="submit" class="btn btn-primary">Potrdi</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Prekliči</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

komorasoft/blueprints/auto/templates/auto/test.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event Timeline</title>
    <link rel="stylesheet" href="{{ url_for('auto.static', filename='css/test.css') }}">
</head>
<body>
    <div class="timeline">
        <div class="event-bar" id="event1">
            <div class="resize-handle left"></div>
            <div class="resize-handle right"></div>
            <div class="event-content">Event 1</div>
        </div>
        <div class="event-bar" id="event2">
            <div class="resize-handle left"></div>
            <div class="resize-handle right"></div>
            <div class="event-content">Event 2</div>
        </div>
    </div>
    <script type="text/babel" src="{{ url_for('auto.static', filename='js/script.js') }}"></script>
</body>
</html> -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resizable Element</title>
    <link rel="stylesheet" href="{{ url_for('auto.static', filename='css/test.css') }}">
</head>
<body>
    <div class="container">
        <div class="resizable-box">
            <!-- <div class="resize-handle top-left"></div>
            <div class="resize-handle top-right"></div>
            <div class="resize-handle bottom-left"></div>
            <div class="resize-handle bottom-right"></div> -->
            <!-- New handles for left and right resizing -->
            <div class="resize-handle left"></div>
            <div class="resize-handle right"></div>
        </div>
    </div>
    <div id="tooltip" class="tooltip"></div>
    <script src="{{ url_for('auto.static', filename='js/script.js') }}"></script>
</body>
</html>